name: appcup
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  firebase_storage: ^3.1.3
  file_picker: ^1.4.3+2
  provider: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: GillSansMT
      fonts:
        - asset: assets/fonts/gillsansmt.TTF
        - asset: assets/fonts/gillsansmt_Bold.TTF
        - asset: assets/fonts/gillsansmt_Condensed.TTF
        - asset: assets/fonts/gillsansmt_Italic.TTF
          style: normal

  assets:
    - assets/images/
  uses-material-design: true
